sudo: false
language: java
jdk: oraclejdk7
install: mvn clean install -DskipTests=true -Dgpg.skip=true
after_success: 
    - bash <(curl -s https://codecov.io/bash)
branches:
  only:
    - master