sudo: false
language: java
jdk: oraclejdk7
before_install:
    - pip install --user codecov
install: mvn clean install -DskipTests=true -Dgpg.skip=true
after_success: 
    - bash <(curl -s https://codecov.io/bash) -t 98daa5d2-3e39-4b73-9f1f-950d7d9e4b57
branches:
  only:
    - master